version: "3.5"
services:
  database:
    image: postgres:16
    container_name: database
    expose:
      - "5433"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=server
